# Generated by Django 2.2.1 on 2019-09-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusresale', '0002_auto_20190829_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
